"""database update

Revision ID: 004221705a80
Revises: beb78785be60
Create Date: 2023-07-30 15:23:24.128663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004221705a80'
down_revision = 'beb78785be60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
