"""empty message

Revision ID: 03689bad89bc
Revises: 656c4a4f511f
Create Date: 2023-08-14 10:15:22.707441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03689bad89bc'
down_revision = '656c4a4f511f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_uses_before_maintenance', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('max_uses_before_maintenance')

    # ### end Alembic commands ###
