"""empty message

Revision ID: 129c7bbb84bb
Revises: 
Create Date: 2023-08-27 16:56:31.493056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129c7bbb84bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
