"""database update

Revision ID: 1bee2dc5a9fd
Revises: 
Create Date: 2023-07-31 09:46:52.720645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bee2dc5a9fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_vehicle')
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_maintenance_date', sa.Date(), nullable=True))
        batch_op.alter_column('brand',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('maintenance',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('maintenance_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maintenance_date', sa.DATE(), nullable=True))
        batch_op.alter_column('maintenance',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('model',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('brand',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('last_maintenance_date')

    op.create_table('_alembic_tmp_vehicle',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('last_maintenance_date', sa.DATE(), nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=5), nullable=False),
    sa.Column('brand', sa.VARCHAR(length=50), nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('price_per_day', sa.FLOAT(), nullable=False),
    sa.Column('next_maintenance_date', sa.DATE(), nullable=True),
    sa.Column('maintenance', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
