"""empty message

Revision ID: 2a1035f7dd5c
Revises: 
Create Date: 2023-09-02 16:24:11.959357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1035f7dd5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veiculo')
    op.drop_table('cliente')
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'veiculos', ['fk_reservation_vehicle'], ['id'])
        batch_op.create_foreign_key(None, 'clientes', ['fk_reservation_customer'], ['id'])

    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'categorias', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('categoria_id')

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'cliente', ['fk_reservation_customer'], ['id'])
        batch_op.create_foreign_key(None, 'veiculo', ['fk_reservation_vehicle'], ['id'])

    op.create_table('cliente',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('apelido', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('data_nascimento', sa.DATE(), nullable=False),
    sa.Column('morada', sa.VARCHAR(length=200), nullable=False),
    sa.Column('nif', sa.INTEGER(), nullable=False),
    sa.Column('price_per_day', sa.FLOAT(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nif')
    )
    op.create_table('veiculo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=5), nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('price_per_day', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=50), nullable=False),
    sa.Column('in_maintenance', sa.BOOLEAN(), nullable=True),
    sa.Column('last_maintenance_date', sa.DATE(), nullable=True),
    sa.Column('next_maintenance_date', sa.DATE(), nullable=True),
    sa.Column('maintenance_history', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('last_legalization_date', sa.DATE(), nullable=True),
    sa.Column('next_legalization_date', sa.DATE(), nullable=True),
    sa.Column('legalization_history', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('imagens', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('available_from', sa.DATE(), nullable=True),
    sa.Column('num_uses', sa.INTEGER(), nullable=True),
    sa.Column('max_uses_before_maintenance', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
