"""empty message

Revision ID: 656c4a4f511f
Revises: 
Create Date: 2023-08-14 01:35:43.051146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656c4a4f511f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_from', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('num_uses', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('num_uses')
        batch_op.drop_column('available_from')

    # ### end Alembic commands ###
