"""database update

Revision ID: 71ae5e5c0377
Revises: 9a4c303852c3
Create Date: 2023-07-31 00:06:42.298261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ae5e5c0377'
down_revision = '9a4c303852c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=20), nullable=False))
        batch_op.drop_column('category')
        batch_op.drop_column('daily_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_value', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
