"""database update

Revision ID: 7bb267cd108e
Revises: 
Create Date: 2023-07-26 17:10:46.501655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb267cd108e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carro', sa.Column('imagens', sa.String(length=255), nullable=True))
    op.add_column('mota', sa.Column('imagens', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mota', 'imagens')
    op.drop_column('carro', 'imagens')
    # ### end Alembic commands ###
