"""empty message

Revision ID: 7ef04a30ba87
Revises: 
Create Date: 2023-09-05 18:43:16.177545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef04a30ba87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_apelido'), ['apelido'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_clientes_nif'), ['nif'], unique=True)
        batch_op.create_index(batch_op.f('ix_clientes_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_telefone'), ['telefone'], unique=False)

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservation_fk_reservation_customer'), ['fk_reservation_customer'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_fk_reservation_vehicle'), ['fk_reservation_vehicle'], unique=False)

    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veiculos_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_veiculos_model'), ['model'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veiculos_model'))
        batch_op.drop_index(batch_op.f('ix_veiculos_brand'))

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_fk_reservation_vehicle'))
        batch_op.drop_index(batch_op.f('ix_reservation_fk_reservation_customer'))

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_telefone'))
        batch_op.drop_index(batch_op.f('ix_clientes_nome'))
        batch_op.drop_index(batch_op.f('ix_clientes_nif'))
        batch_op.drop_index(batch_op.f('ix_clientes_email'))
        batch_op.drop_index(batch_op.f('ix_clientes_apelido'))

    # ### end Alembic commands ###
