"""database update

Revision ID: af7d182eab27
Revises: 71ae5e5c0377
Create Date: 2023-07-31 01:29:45.077195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af7d182eab27'
down_revision = '71ae5e5c0377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_maintenance_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('next_maintenance_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('next_maintenance_date')
        batch_op.drop_column('last_maintenance_date')

    # ### end Alembic commands ###
