"""database update

Revision ID: bc47e0924781
Revises: 
Create Date: 2023-07-30 17:16:55.262301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc47e0924781'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('daily_value', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('is_available')
        batch_op.drop_column('daily_value')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
