"""empty message

Revision ID: be53a9a227a5
Revises: deb9c8c6cc16
Create Date: 2023-08-27 11:11:24.562186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be53a9a227a5'
down_revision = 'deb9c8c6cc16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.TIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Time(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.Date(),
               type_=sa.TIME(),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
