"""database update

Revision ID: d176e0b11016
Revises: 
Create Date: 2023-07-23 14:49:57.222393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd176e0b11016'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carro', sa.Column('imagem', sa.String(length=200), nullable=True))
    op.add_column('mota', sa.Column('imagem', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mota', 'imagem')
    op.drop_column('carro', 'imagem')
    # ### end Alembic commands ###
